remote_theme: pages-themes/cayman@v0.2.0
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Git guide
description: A short git guide with basic operations

show_downloads: "false"
